name: GitHub Actions Demo
on: 
  push:
    branches: 
    - main
    paths-ignore: 
    - .github/**
  pull_request:
    branches: 
    - main 
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  my-build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Echo event name & branch name
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"
      - name: List files in the repository
        run: |
          echo "Files:"
          tree
